config/routes.rb
Rails.application.routes.draw do

  resources :stories do
    resources :votes do
    end
  end

resource :session
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/story.rb
class Story < ApplicationRecord
  validates :name, :link, presence: true

  belongs_to :user
  has_many :votes do
    def latest
      order('id DESC').limit(3)
    end
  end

  def to_param
    "#{id}-#{name.gsub(/\W/, '-').downcase}"
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :stories
  has_many :votes
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :story
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :current_user

  protected

  def ensure_login
    return true if logged_in?
    session[:return_to] = request.fullpath
    redirect_to new_session_path and return false
  end

  def current_user
    return unless session[:user_id]
    @current_user = User.where(id: session[:user_id]).first
  end
  def logged_in?
    !@current_user.nil?
  end
    helper_method :logged_in?
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @current_user = User.find_by(email: params[:email])
    if @current_user && @current_user.authenticate(params[:password])
      session[:user_id] = @current_user.id
      if session[:return_to]
        redirect_to session[:return_to]
        session[:return_to] = nil
      else
      redirect_to stories_path
          end
        end
  end

  def destroy
    session[:user_id] = @current_user = nil

  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :ensure_login, only: [ :new, :create ]
  def create
    @story = @current_user.stories.build story_params
  if  @story.save
    flash[:notice] = "Story submission succeeded"
    redirect_to stories_path
  else
    render action:'new'
  end
end

  def index
    @story = Story.order('RANDOM()').first
  end

  def new
    @story = Story.new
  end

  def story_params
    params.require(:story).permit(:name, :link)
  end

def show
  @story = Story.find(params[:id])
end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    @story = Story.find(params[:story_id])
    @story.votes.create(user: @current_user)
    respond_to do |format|
      format.html { redirect_to @story, notice: 'Vote was successfully created.'}
      format.js {}
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Readit</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>

  <body>
    <div id= "content">
      <div id="login_logout">
    <% if @current_user %>
      Logged in as:
      <%= @current_user.name %>
      <em><%= link_to "(Logout)", session_path,
          method: :delete %></em>
        <% else %>
      <em>Not logged in.</em>
      <%= link_to 'Login', new_session_path %>
    <% end %>
  </div>

      <h1> Readit</h1>
      <% unless flash[:notice].blank? %>
      <div id= "notification"><%= flash[:notice] %></div>

      <% end %>
    <%= yield %>
  </div>

  <ul id="navigation">
    <li><%= link_to 'Front page stories', stories_path %></li>
    <li><%= link_to 'Submit a new story!', new_story_path %></li>
      </ul>
    </body>

</html>

app/views/stories/create.js.erb
$("#vote_score").html("Score: " + <%= @story.votes.size %>)
$("#vote_score").css({backgroundColor: "#ffffcc"});

setTimeout(function(){
  $("#vote_score").css({backgroundColor: "#ffffff"});
}, 2000);

app/views/stories/index.html.erb
A random link:
<%= link_to @story.name, @story %>

app/views/stories/new.html.erb
<% if @story.errors.any? %>
  <div class="form_errors">
    <h3>Errors</h3>
    <ul>
      <% @story.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
            </ul>
          </div>
        <% end %>

<%= form_for @story do |f| %>
  <div>
  <p><%= f.label :name %></p>
  <%= f.text_field :name %>
</div>
<div>
  <p><%= f.label :link %></p>
  <%= f.text_field :link %>
</div>
<%= submit_tag %>
<% end %>

app/views/stories/show.html.erb
<h2>
  <span id= "vote_score">
    Score: <%= @story.votes.size %>
  </span>
  <%= @story.name %>
</h2>

<ul id="vote_history">
  <% if @story.votes.empty? %>
    <em> No votes yet! </em>
  <% else %>
    <%= render partial: 'votes/vote',
        collection: @story.votes.latest %>
  <% end %>
  </ul>

  <p class="submitted_by">
    Submitted by:
    <span><%= @story.user.name %></span>
    </p>

<p>
<%= link_to @story.link, @story.link %>
</p>
<div id= "vote_form">
  <%= form_tag story_votes_path(@story), remote: true do %>
  <%= submit_tag 'Vote for it' %>
  <% end %>
</div>

app/views/votes/_vote.html.erb
><li><%= vote.created_at.to_formatted_s(:short) %></li>

app/views/votes/create.html.erb
<h1>Votes#create</h1>
<p>Find me in app/views/votes/create.html.erb</p>

app/views/votes/create.js.erb
$("#vote_score").html("Score: " + <%= @story.votes.size %>)
$("#vote_score").css({backgroundColor: "#ffffcc"});
$("#vote_history").html('<%= j(render partial: "votes/vote",
collection: @story.votes.latest) %>')

setTimeout(function(){
  $("#vote_score").css({backgroundColor: "#ffffff"});
}, 2000);